// app/jemma-lite/types.ts
//
//shared type definitions for Jemma Lite chat page.
//keep serverevevnt in sync with sse event names emittd by
//src//server/main.cpp on the C++ Jemma Server

export type Role = "user" | "assistant" | "tool";
export type ToolStatus  = "running" | "done" | "error";
/**
 * what we render in the message list.  Each message has a stable
 * id so React can ket it correctly across re-renders during streaming.
 */
export type Message =
    | {
        id: string;
        role: "user"
        content: string;
    }
    | {
        id: string;
        role: "assistant"
        content: string;
        streaming?: boolean; // if true, this message is still being generated by the assistant
    }
    | {
        id: string;
        role: "tool"
        name: string;
        args?: Record<string, unknown>;
        result?: string;
        status: ToolStatus;
    };
/**
 * Decoded SSE event from the Jemma server.
 *
 * The C++ server sends named events:
 *   event: token  | data: {"text": "..."}
 *   event: audio  | data: {"mp3_b64": "..."}
 *   event: done   | data: {}
 *   event: error  | data: {"error": "..."}
 *
 * The `tool_call` / `tool_result` variants are reserved for when you
 * wire tool calls into the engine. The UI already renders them.
 */
export type ServerEvent =
    | { kind: "token"; text: string }
    | { kind: "audio"; mp3_b64: string }
    | { kind: "done" }
    | { kind: "error"; error: string }
    | {
        kind: "tool_call";
        id: string;
        name: string;
        args?: Record<string, unknown>;
    }
    | {
        kind: "tool_result";
        id: string;
        ok: boolean;
        result?: string;
    };
/**
 * Stored auth state. The token comes from POST /auth/login.
 * Username is kept only so we can show "Signed in as ..." in the UI.
 */
export type AuthState =
    | { status: "anonymous"}
    |{ status: "authed"; token: string; username: string };
